apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.spec.type }}
  selector:
    app: {{ .Values.spec.selector.app }}
  ports:
  - name: {{ .Values.ports.name }}
    port: {{ .Values.ports.port }}
    targetPort: {{ .Values.ports.targetPort }}