spec:
  service: 
    type: ClusterIP
containers:
  name: redis
  image: redis:alpine
ports:
  containerPort: 6379
  service:
    name: redis
    port: 6379
    targetPort: 6379
readinessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 6379
livenessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 6379
volumeMounts:
  mountPath: /data
  name: redis-data
resources:
  limits:
    memory: 256Mi
    cpu: 125m
  requests:
    cpu: 70m
    memory: 200Mi
volumes:
  name: redis-data