name: adservice
spec:
  serviceAccount:
    serviceAccountName: default
    terminationGracePeriodSeconds: 5
  service: 
    type: ClusterIP
image:
  server:
    name: server
    repository: gcr.io/google-samples/microservices-demo/adservice:v0.2.4
ports:
  image:
    containerport: 9555
  service: 
    name: grpc
    port: 9555
    targetport: 9555
  env:
    name: PORT
    value: '"9555"'
resources:
  limits:
    cpu: 200m
    memory: 180Mi
  requests:
    cpu: 300m
    memory: 300Mi
probeRL:
  exec:
    initialDelaySeconds: 20
    periodSeconds: 15
