spec:
  serviceAccountName: default
  type: ClusterIP
containers:
  name: server
  image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.2.4
ports:
  containerPort: 5050
  service:
    name: grpc
    port: 5050
    targetPort: 5050
env:
  name: PORT
  value: '"5050"'
  name1: PRODUCT_CATALOG_SERVICE_ADDR
  value1: "productcatalogservice:3550"
  name2: SHIPPING_SERVICE_ADDR
  value2: "shippingservice:50051"
  name3: PAYMENT_SERVICE_ADDR
  value3: "paymentservice:50051"
  name4: EMAIL_SERVICE_ADDR
  value4: "emailservice:5000"
  name5: CURRENCY_SERVICE_ADDR
  value5: "currencyservice:7000"
  name6: CART_SERVICE_ADDR
  value6: "cartservice:7070"
# name: DISABLE_STATS
# value: "1"
# name: DISABLE_TRACING
# value: "1"
# name: DISABLE_PROFILER
# value: "1"
# name: JAEGER_SERVICE_ADDR
# value: "jaeger-collector:14268"
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi