apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.spec.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: {{ .Values.ports.service.name }}
    port: {{ .Values.ports.service.port }}
    targetPort: {{ .Values.ports.service.targetPort }}