spec:
  serviceAccountName: default
  terminationGracePeriodSeconds: 5
  type: ClusterIP
containers:
  name: server
  image: gcr.io/google-samples/microservices-demo/cartservice:v0.2.4
ports:
  containerPort: 7070
  service:
    name: grpc
    port: 7070
    targetPort: 7070
env:
  name: REDIS_ADDR
  value: '"redis-cart:6379"'
resources:
  requests:
    cpu: 200m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 128Mi
readinessProbe:
  initialDelaySeconds: 15
livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 10