apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.spec.serviceAccountName }}
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.image }}
          ports:
          - containerPort: {{ .Values.ports.containerPort }}
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          env:
          - name: {{ .Values.env.name }}
            value: {{ .Values.env.value }}
          - name: {{ .Values.env.name1 }}
            value: {{ .Values.env.value1 }}
          - name: {{ .Values.env.name2 }}
            value: {{ .Values.env.value2 }}
          - name: {{ .Values.env.name3 }}
            value: {{ .Values.env.value3 }}
          - name: {{ .Values.env.name4 }}
            value: {{ .Values.env.value4 }}
          - name: {{ .Values.env.name5 }}
            value: {{ .Values.env.value5 }}
          - name: {{ .Values.env.name6 }}
            value: {{ .Values.env.value6 }}
          # - name: DISABLE_STATS
          #   value: "1"
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: DISABLE_PROFILER
          #   value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}