spec:
  serviceAccountName: default
  terminationGracePeriodSeconds: 5
  service:
    type: ClusterIP
containers:
  name: server
  image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.2.4
ports:
  containerPort: 3550
  service:
    name: grpc
    port: 3550
    targetPort: 3550
env:
  name: PORT
  value: '"3550"'
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi