spec:
  serviceAccountName: default
  service:
    type: ClusterIP
containers:
  name: server
  image: gcr.io/google-samples/microservices-demo/shippingservice:v0.2.4
ports:
  containerPort: 50051
  service:
    name: grpc
    port: 50051
    targetPort: 50051
env:
  name: PORT
  value: '"50051"'
  # - name: DISABLE_STATS
  #   value: "1"
  # - name: DISABLE_TRACING
  #   value: "1"
  # - name: DISABLE_PROFILER
  #   value: "1"
  # - name: JAEGER_SERVICE_ADDR
  #   value: "jaeger-collector:14268"
readinessProbe:
  periodSeconds: 5
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi